# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\git\ftpAdmin\FTPAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 285)
        MainWindow.setMinimumSize(QtCore.QSize(0, 285))
        MainWindow.setMaximumSize(QtCore.QSize(800, 285))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_ipAddr = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ipAddr.setMinimumSize(QtCore.QSize(127, 0))
        self.lineEdit_ipAddr.setMaximumSize(QtCore.QSize(127, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_ipAddr.setFont(font)
        self.lineEdit_ipAddr.setReadOnly(False)
        self.lineEdit_ipAddr.setObjectName("lineEdit_ipAddr")
        self.horizontalLayout_3.addWidget(self.lineEdit_ipAddr)
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_username.setText("")
        self.lineEdit_username.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout_3.addWidget(self.lineEdit_username)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.lineEdit_passwd = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_passwd.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_passwd.setText("")
        self.lineEdit_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_passwd.setObjectName("lineEdit_passwd")
        self.horizontalLayout_3.addWidget(self.lineEdit_passwd)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_add.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_4.addWidget(self.pushButton_add)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_4.addWidget(self.pushButton_clear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_model = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_model.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_model.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_model.setFont(font)
        self.lineEdit_model.setText("")
        self.lineEdit_model.setReadOnly(False)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.horizontalLayout_5.addWidget(self.lineEdit_model)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_customer = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_customer.setMinimumSize(QtCore.QSize(127, 0))
        self.lineEdit_customer.setMaximumSize(QtCore.QSize(127, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_customer.setFont(font)
        self.lineEdit_customer.setText("")
        self.lineEdit_customer.setReadOnly(False)
        self.lineEdit_customer.setObjectName("lineEdit_customer")
        self.horizontalLayout_5.addWidget(self.lineEdit_customer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(64, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_user = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_user.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_user.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setText("")
        self.lineEdit_user.setReadOnly(True)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.horizontalLayout_6.addWidget(self.lineEdit_user)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(48, 0))
        self.label_10.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_pwd.setMinimumSize(QtCore.QSize(127, 0))
        self.lineEdit_pwd.setMaximumSize(QtCore.QSize(127, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_pwd.setFont(font)
        self.lineEdit_pwd.setText("")
        self.lineEdit_pwd.setReadOnly(True)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.horizontalLayout_6.addWidget(self.lineEdit_pwd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 29))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.comboBox_userList = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_userList.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_userList.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_userList.setFont(font)
        self.comboBox_userList.setObjectName("comboBox_userList")
        self.horizontalLayout.addWidget(self.comboBox_userList)
        self.pushButton_refresh = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_refresh.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_refresh.setFont(font)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout.addWidget(self.pushButton_refresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.lineEdit_newPasswd = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_newPasswd.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_newPasswd.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_newPasswd.setFont(font)
        self.lineEdit_newPasswd.setText("")
        self.lineEdit_newPasswd.setReadOnly(False)
        self.lineEdit_newPasswd.setObjectName("lineEdit_newPasswd")
        self.horizontalLayout_9.addWidget(self.lineEdit_newPasswd)
        self.pushButton_update = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_update.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_update.setFont(font)
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout_9.addWidget(self.pushButton_update)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.lineEdit_filePath = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit_filePath.setFont(font)
        self.lineEdit_filePath.setText("")
        self.lineEdit_filePath.setObjectName("lineEdit_filePath")
        self.horizontalLayout_13.addWidget(self.lineEdit_filePath)
        self.pushButton_openPath = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_openPath.setFont(font)
        self.pushButton_openPath.setObjectName("pushButton_openPath")
        self.horizontalLayout_13.addWidget(self.pushButton_openPath)
        self.pushButton_up = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_up.setFont(font)
        self.pushButton_up.setObjectName("pushButton_up")
        self.horizontalLayout_13.addWidget(self.pushButton_up)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setMinimumSize(QtCore.QSize(150, 0))
        self.label_15.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.label_downloadPath = QtWidgets.QLabel(self.centralWidget)
        self.label_downloadPath.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_downloadPath.setFont(font)
        self.label_downloadPath.setText("")
        self.label_downloadPath.setObjectName("label_downloadPath")
        self.horizontalLayout_7.addWidget(self.label_downloadPath)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.lineEdit_filePath.raise_()
        self.label_14.raise_()
        self.pushButton_openPath.raise_()
        self.pushButton_up.raise_()
        self.label_downloadPath.raise_()
        self.label_15.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 745, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP User Management"))
        self.label_2.setText(_translate("MainWindow", "IP地址"))
        self.lineEdit_ipAddr.setText(_translate("MainWindow", "10.110.30.86"))
        self.label_8.setText(_translate("MainWindow", "用户名"))
        self.label_9.setText(_translate("MainWindow", "登陆密码"))
        self.label_3.setText(_translate("MainWindow", "新增项目及用户"))
        self.pushButton_add.setText(_translate("MainWindow", "新增"))
        self.pushButton_clear.setText(_translate("MainWindow", "清除"))
        self.label_4.setText(_translate("MainWindow", "设备型号"))
        self.label_5.setText(_translate("MainWindow", "运营商"))
        self.label_7.setText(_translate("MainWindow", "用户名"))
        self.label_10.setText(_translate("MainWindow", "密码"))
        self.label_6.setText(_translate("MainWindow", "更新用户密码"))
        self.label_11.setText(_translate("MainWindow", "用户名"))
        self.pushButton_refresh.setText(_translate("MainWindow", "刷新"))
        self.label_12.setText(_translate("MainWindow", "新密码"))
        self.pushButton_update.setText(_translate("MainWindow", "更新"))
        self.label_14.setText(_translate("MainWindow", "选择上传文件路径"))
        self.pushButton_openPath.setText(_translate("MainWindow", "浏览"))
        self.pushButton_up.setText(_translate("MainWindow", "上传"))
        self.label_15.setText(_translate("MainWindow", "上传文件的下载地址"))
        self.menu.setTitle(_translate("MainWindow", "关于"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

